FROM node:alpine
#MAINTAINER Keymetrics <contact@keymetrics.io>
#WORKDIR /app
#EXPOSE 3000

#RUN npm install
#RUN npm install pm2 -g
#RUN npm install koa-views 
#RUN npm install koa
#RUN npm install koa-logger
#RUN npm install koa-body
#RUN npm install koa-router

#COPY .
#VOLUME ["/app"]


# Start process.yml
#CMD ["pm2-docker", "start", "--auto-exit", "--env", "production", "process.yml"]
